# ###############
# ## 
# ####

# GPU: [0,1,2,3]

# VERBOSE: True

# MODEL:
#   MODE: 'Denoising'
#   SESSION: 'MPRNet'

# # Optimization arguments.
# OPTIM:
#   BATCH_SIZE: 16
#   NUM_EPOCHS: 80
#   # NEPOCH_DECAY: [10]
#   LR_INITIAL: 2e-4
#   LR_MIN: 1e-6
#   # BETA1: 0.9

# TRAINING:
#   VAL_AFTER_EVERY: 1
#   RESUME: False
#   TRAIN_PS: 128
#   VAL_PS: 196
#   TRAIN_DIR: './Datasets/train' # path to training data
#   VAL_DIR: './Datasets/val'     # path to validation data
#   SAVE_DIR: './checkpoints'          # path to save models and images
#   # SAVE_IMAGES: False

###############
## 
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'CS'
  SESSION: 'MPRNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 16 
  NUM_EPOCHS: 250
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 5
  RESUME: False
  TRAIN_PS: 128
  VAL_PS: 128
  TRAIN_DIR: './Datasets/train' # path to training data
  VAL_DIR: './Datasets/val'     # path to validation data
  SAVE_DIR: './checkpoints'          # path to save models and images
  # SAVE_IMAGES: False