###############
## 
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'Deblurring'
  SESSION: 'DGUNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 16
  NUM_EPOCHS: 3000
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 10
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: '/userhome/DGUNet/Deblurring/Datasets/GoPro/train' # path to training data
  VAL_DIR: '/userhome/DGUNet/Deblurring/Datasets/GoPro/test'    # path to validation data
#   TRAIN_DIR: './Datasets/train' # path to training data
#   VAL_DIR: './Datasets/test'    # path to validation data
  SAVE_DIR: './checkpoints'     # path to save models and images
  # SAVE_IMAGES: False